# Generated by Django 3.1 on 2021-03-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
